name: Provide precompiled OTP release assets

on:
  workflow_dispatch:
    inputs:
      target-pattern:
        description: "A pattern to provide"
        required: true
      force-update:
        description: "Force update if true"
        required: false
jobs:
  provide-precompiled-otp-release-assets:
    name: A job to setup otp
    strategy:
      matrix:
        os:
          - macos-latest
          # - ubuntu-latest
          # - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0
      - name: Provide precompiled OTP release assets
        uses: niku/otp-kuroko@master
        with:
          secret-token: ${{ secrets.GITHUB_TOKEN }}
          target-pattern: ${{ github.event.inputs.target-pattern }}
