name: Repo sync

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/erlang/otp.git
          source_branch: "*"
          destination_branch: "*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
        cat  << 'EOF' > .github/workflows/main.yml
        name: CI

        on: [push]

        jobs:
          setup-otp:
            name: A job to setup otp
            strategy:
              matrix:
                os:
                  - macos-latest
                  # - ubuntu-latest
                  # - windows-latest
                otp-version:
                  - "OTP-23.0"
              fail-fast: false
            runs-on: ${{ matrix.os }}
            steps:
              - name: Checkout
                uses: actions/checkout@v2
                with:
                  ref: ${{ matrix.otp-version }}
              - name: Setup OTP

                uses: niku/otp-kuroko@master
                with:
                  secret-token: ${{ secrets.GITHUB_TOKEN }}
        EOF
      - run: cat .github/workflows/main.yml
