name: Make repository sync

on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: erlang/otp
          source_branch: master
          destination_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
