name: Make repository sync

on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: https://github.com/erlang/otp
          source_branch: "*"
          destination_branch: "*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
