name: Repo sync

on:
  schedule:
    - cron: "23 6 * * *"

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: repo-sync
        uses: wei/git-sync@v2
        with:
          source_repo: erlang/otp
          source_branch: "refs/tags/*"
          destination_repo: niku/otp
          destination_branch: "refs/tags/*"
